theme: minima
url: https://jgte.github.io/gswarm
# https://stackoverflow.com/questions/17207458/how-to-add-google-analytics-tracking-id-to-github-pages
plugins:
  - jekyll-seo-tag
google_analytics: UA-140095141-2

# add a new file to your repository root named Gemfile with this content:
# source "https://rubygems.org”
# gem "github-pages", group: :jekyll_plugins
# gem 'jekyll-seo-tag'